### ISSUE TITLE
Strata change possible?

### ISSUE THREAD

**Issue by cosmo-somebody** [PunishedPineapple/Distance#1]
would it be possible to change the strata so that the widget is not overlaying the top of regular game windows?

![Screenshot 2022-05-01 180315](https://user-images.githubusercontent.com/103899995/166168119-30c79a1e-fb11-4723-9f55-0ec8e16f5ea8.png)

**Comment by PunishedPineapple** [comment]
So right now, the widgets are attached to the `ScreenText` addon, since that's basically the only addon that is guaranteed to be enabled by any given user.  The problem is, as you see, that addon is always visible, and always on top haha.  I was planning to look into adding an option to attach the widgets to target bar, focus target bar, etc. addons at some point.  So the short answer to your question is probably, but don't expect anything immediately, as most of my free time is going to be going toward raid-related things for the next few weeks.

**Comment by PunishedPineapple** [comment]
@cosmo-somebody I added options for this in version 0.9.6.0.  It should be automatic when the plugin is updated, but you'll need to reset the positions of any widgets that you have, as binding to different UI elements means that the relative coordinates won't be the same anymore.  Sorry for the inconvenience.

Also, this plugin was accepted into Dalamud testing, so it's no longer on my third party repo.  Enable plugin testing in `/xlsettings` to get the current version once the PR gets merged.
