### ISSUE TITLE
Bug Report: Show Distance on Name Plates

### ISSUE THREAD

**Issue by werewolfboy13** [PunishedPineapple/Distance#11]
Show Distance on Name Plates check box does not work. Will send an error in logs. 

This is in version: V1.0.1.2

![image](https://user-images.githubusercontent.com/43587009/211959539-65aa65cc-9f9b-49b4-9be3-74a6cc18f41e.png)
![image](https://user-images.githubusercontent.com/43587009/211959563-184a4402-8b0c-4af7-9a70-d6b6deacb162.png)

**Comment by PunishedPineapple** [comment]
Ya, nameplate stuff in ClientStructs needs to be updated for patch 6.3.  It's being worked on, but there were a lot of changes to the game with this patch, and nameplates tend to be lower priority I think than the dependencies of more widely-used plugins.  One of the CS maintainers said that he'd look into it even though he's on vacation, so I'm certainly not going to complain.

Anyway, sorry for the trouble, but at this point, nameplates should probably just be assumed broken after patches, since those structs seem to change half the time.

**Comment by PunishedPineapple** [comment]
ClientStructs has been updated, and nameplates work again.
