### ISSUE TITLE
Option to hide distance display at a certain threshold

### ISSUE THREAD

**Issue by colopatiron** [PunishedPineapple/Distance#22]
Can we have an option to hide the distance display when you're past a certain threshold? For example, I don't want to see the number when I'm less than 3 yalms, or right on top of the target.

**Comment by PunishedPineapple** [comment]
Sure.  I actually did basically this for custom arcs in the pending testing release, so if/when that gets merged, I'll add distance-based fading for the text readouts and aggro arc as well.

**Comment by PunishedPineapple** [comment]
This is now in the latest version.  For the use case that you mentioned, you will want to go into your settings for fading, and configure it something like this (for whichever readouts/arcs you want):

![image](https://github.com/PunishedPineapple/Distance/assets/50609717/c073d1e9-a0c7-4f48-935c-e0d16af70fba)

Fading did not get implemented for the aggro distances yet because those need additional changes, but that should not matter for your stated use case at least.
