### ISSUE TITLE
Wrong numbers in nameplates.

### ISSUE THREAD

**Issue by yrusabu** [PunishedPineapple/Distance#9]
After the game update or Dalamud update. The plugin started acting weird. Showing wrong numbers or not showing nothing at all in the nameplates. After reinstalling, disabling the plugin or even exiting the game the problem still persists.
![Screenshot 2022-10-21 024900](https://user-images.githubusercontent.com/116336997/197143197-7e47b062-d07e-4c6b-a09b-d61c3d48de8a.png)
![Screenshot 2022-10-21 024838](https://user-images.githubusercontent.com/116336997/197143219-ea2114be-abeb-4c36-a04b-735674298a38.png)

**Comment by erickt420** [comment]
I am experiencing the same issue. Seems like only 1 random nameplate shows the distance but it's showing the distance of a different target.

**Comment by NuckChorris** [comment]
This seems related to #6, I think there might be some situation which causes it to mix up the objects of the nameplates

**Comment by reibitto** [comment]
I'm having this issue too ever since version 6.21. Most numbers don't show up anymore for me, and when one does it'll be in a random location on my screen not next to anything relevant.

There was another comment in the other linked issue about possibly issues with the installer or multiple instances of the plugin running, but I did a full uninstall of the plugin (and made sure to delete and leftover files/folders) then reinstalled but that didn't fix it either.

I'm not sure if there's a workaround for this for the time being or if it needs to be fixed in code.

**Comment by PunishedPineapple** [comment]
This is unrelated to #6, which I’m considering a fluke since I’ve never seen nor heard of it happening again.

This issue is due to struct changes in the game that came a couple of patches ago, but which were not picked up by the ClientStructs library.  It looks like ClientStructs updated its offsets for that the nameplate stuff on which this plugin relies last night (https://github.com/aers/FFXIVClientStructs/commit/e6a68ae2ab4b9517b9201d97fc0f046b221f4484) and Dalamud picked it up a few hours ago (https://github.com/goatcorp/Dalamud/commit/a173c5dac54fa4b55f5c5066bdcd93cbbcd74ed9).  Once a new version of Dalamud is on peoples computers with the updated structure, I’ll submit an update that will rebuild this plugin against the current structs if necessary.

**Comment by PunishedPineapple** [comment]
It looks like the client structs update got deployed with the latest Dalamud release this morning.  Nameplates should work again.  I am sorry for how long it took; I do not know how to ask the maintainers to update that dependency when this happens without sounding like a pest.

**Comment by reibitto** [comment]
Can confirm it's working now. Thanks!
